"use strict";

gameEngine.assets = [{
    id: "wep",
    type: "binary",
    src: "data/wep.etx"
}, {
    id: "type",
    type: "binary",
    src: "data/type.etx"
}, {
    id: "item",
    type: "binary",
    src: "data/item.etx"
}, {
    id: "config",
    type: "text",
    src: "data/mortar.cfg"
}, {
    id: "backbot.pcx",
    src: "gfx/backbot.png"
}, {
    id: "backtop.pcx",
    src: "gfx/backtop.png"
}, {
    id: "menubot.pcx",
    src: "gfx/menubot.png"
}, {
    id: "menutop.pcx",
    src: "gfx/menutop.png"
}, {
    id: "menuback.pcx",
    src: "gfx/menuback.png"
}, {
    id: "frame.pcx",
    src: "gfx/frame.png"
}, {
    id: "bar.pcx",
    src: "gfx/bar.png"
}, {
    id: "weplist.pcx",
    src: "gfx/weplist.png"
}, {
    id: "wep01.pcx",
    src: "gfx/wep01.png"
}, {
    id: "wep02.pcx",
    src: "gfx/wep02.png"
}, {
    id: "wep03.pcx",
    src: "gfx/wep03.png"
}, {
    id: "wep04.pcx",
    src: "gfx/wep04.png"
}, {
    id: "wep05.pcx",
    src: "gfx/wep05.png"
}, {
    id: "wep06.pcx",
    src: "gfx/wep06.png"
}, {
    id: "wep07.pcx",
    src: "gfx/wep07.png"
}, {
    id: "wep08.pcx",
    src: "gfx/wep08.png"
}, {
    id: "wep09.pcx",
    src: "gfx/wep09.png"
}, {
    id: "wep10.pcx",
    src: "gfx/wep10.png"
}, {
    id: "wep11.pcx",
    src: "gfx/wep11.png"
}, {
    id: "wep12.pcx",
    src: "gfx/wep12.png"
}, {
    id: "wep13.pcx",
    src: "gfx/wep13.png"
}, {
    id: "wep14.pcx",
    src: "gfx/wep14.png"
}, {
    id: "wep15.pcx",
    src: "gfx/wep15.png"
}, {
    id: "wep16.pcx",
    src: "gfx/wep16.png"
}, {
    id: "wep17.pcx",
    src: "gfx/wep17.png"
}, {
    id: "wep18.pcx",
    src: "gfx/wep18.png"
}];
