"use strict";

gameEngine.assets = [{
    id: "wep",
    type: "binary",
    src: "data/wep.etx"
}, {
    id: "type",
    type: "binary",
    src: "data/type.etx"
}, {
    id: "item",
    type: "binary",
    src: "data/item.etx"
}, {
    id: "config",
    type: "text",
    src: "data/mortar.cfg"
}, {
    id: "backbot.pcx",
    src: "gfx/backbot.png"
}, {
    id: "backtop.pcx",
    src: "gfx/backtop.png"
}, {
    id: "menubot.pcx",
    src: "gfx/menubot.png"
}, {
    id: "menutop.pcx",
    src: "gfx/menutop.png"
}, {
    id: "menuback.pcx",
    src: "gfx/menuback.png"
}, {
    id: "frame.pcx",
    src: "gfx/frame.png"
}, {
    id: "bar.pcx",
    src: "gfx/bar.png"
}];
