unit Colors;

interface

  const Black = 0;
        White = 215;
        DarkBlue = 2;
        MedBlue = 4;
        Blue = 5;
        LightBlue = 47;
        BrightBlue = 89;
        DarkRed = 12;
        Red = 18;
        LightRed = 30;
        Pink = 143;
        Cyan = 185;
        DarkCyan = 81;
        LightBrown = 133;
        DarkBrown = 84;
        DarkestBrown = 48;
        Brown = 90;
        LightGray = 129;
        Gray = 86;
        BrightGray = 172;
        DarkGray = 43;
        Yellow = 210;
        LightMagenta = 35;
        Magenta = 28;
        DarkMagenta = 14;
        Green = 180;
        MedGreen = 144;
        DarkGreen = 108;
        DarkestGreen = 72;
        Orange = 138;
        DarkYellow = 174;
        Sky = 1;

implementation

end.